version: "3"

services:
  namenode:
    image: zll5267/hadoop-namenode:${HADOOP_VERSION}
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 9000:9000
      - 50070:50070

  datanode:
    image: zll5267/hadoop-datanode:${HADOOP_VERSION}
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075

  resourcemanager:
    image: zll5267/hadoop-resourcemanager:${HADOOP_VERSION}
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env
    ports:
      - 8088:8088

  nodemanager1:
    image: zll5267/hadoop-nodemanager:${HADOOP_VERSION}
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - 8042:8042

  historyserver:
    image: zll5267/hadoop-historyserver:${HADOOP_VERSION}
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports:
      - 8188:8188

  hbase:
    image: zll5267/hbase-standalone:1.0.0-hbase2.3.5
    hostname: hbase
    container_name: hbase
    volumes:
      - hbase_data:/hbase-data
    depends_on:
       - zookeeper
       - namenode
       - datanode
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hbase-standalone.env

  zookeeper:
    image: zll5267/zookeeper:latest
    volumes:
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 2181:2181

  zkwebui:
    image: zll5267/zookeeper-webui
    environment:
      ZK_DEFAULT_NODE: zookeeper:2181
      HTTP_PORT: 8080
      USER: zll
      PASSWORD: zll
    ports:
      - "28080:8080"

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hbase_data:
  hbase_zookeeper_data:
